### ISSUE TITLE
No files or folders appear

### ISSUE THREAD

**Issue by KeXxDumb** [iZakirSheikh/Gallery#2]
I want to use the app but even giving permission to access the files (it doesn't ask for it by the way, I have to give it manually) no file appears.
![Screenshot_20240924-125429](https://github.com/user-attachments/assets/bb58d27a-41cc-4015-88ee-f3860746f3af)

**Comment by ashraftaha74** [comment]
https://github.com/iZakirSheikh/Gallery/issues/8
